/* Main.c file generated by New Project wizard
 *
 * Created:   ?? 6? 30 2017
 * Processor: 80C51
 * Compiler:  Keil for 8051
 */

#include <reg51.h>
#include <stdio.h>
#include<intrins.h> 
#include<absacc.h>
#define uchar unsigned char
#define uint unsigned int


void DelayMS(uint x) ;//MS??
//*************************************************************************
//******************************????*********************************
//*************************************************************************
uchar speed;//??????
sbit P10 = P1^0;
sbit P11 = P1^1;
sbit P12 = P1^2;
sbit P13 = P1^3;
sbit P14 = P1^4;
sbit P15 = P1^5;

sbit P17 = P1^7;
/*#define A P10
#define B P11
#define C P12
#define D P13*/
/*#define    s_A        {A = 1;B = 0;C = 0;D = 0;}
#define    s_B        {A = 0;B = 1;C = 0;D = 0;}
#define    s_C        {A = 0;B = 0;C = 1;D = 0;}
#define    s_D        {A = 0;B = 0;C = 0;D = 1;}
#define    s_OFF      {A = 0;B = 0;C = 0;D = 0;}
*/
/*Button define*/
uint level=0;
bit p_status=0;
bit on_off = 1; // Control the motor on and off;
bit auto_mode = 0; // self-control mode
bit set_time_mode = 0; // time_set_control mode
uint code DA_LEVEL[]={128,144,160,176,192,208,224,240,255};
xdata unsigned char DACS _at_ 0x9000;
void myint0();
/*Button define*/
/* timer define*/
uint timer_count = 0;
uint left_time = 0;
/* timer define*/

//*************************************************************************
//******************************???\????******************************
//*************************************************************************
#define my_data_B XBYTE[0X8001] //????  8001??????
uchar code SEGCC[]={0x3f,0x06,0x5b,0x4f,0x66,0x6d,0x7d,0x07,0x7f,0x6f,0x77,0x7c,0x39,0x5e,0x79,0x71,0x40}; //0x40 -->'-'
uchar code SEGLOCAL[]={0x40,0x20,0x10,0x08,0x04,0x02,0x01}; // ?????
uchar xdata *DIGIT;//??
uchar xdata *SEG;//??
uchar xdata *KEYIN;//??
uchar testkey();//????????
uchar scankey();//????????
void showkey(uchar b,uchar pos);//??
//*************************************************************************
//******************************ADC????*********************************
//*************************************************************************
#define my_data_ADC0 XBYTE[0XA000] //?AD????
uchar xdata *ADCS;
uchar adresult;//ad????
void readADC();

//*************************************************************************
//******************************????************************************
//*************************************************************************
uchar status;// 0?? 1?? 2??
char data now_temperature;//????
uchar time;
void myinit()//????????
{
   //??0????????
   EX1=1;
   ET1=1;

   EA=1;
   DIGIT=0x8002;
   SEG=0x8004;
   KEYIN=0x8001;
   ADCS=0xa000;
   speed=10;
   time=10;
   now_temperature=0;
}
/* time set function*/
void init_time()
{
	left_time = 5; // stop after 5s
	TMOD=0x01;
	TH0=(65536-50000)/256;
	TL0=(65536-50000)%256;
	EA=1;
	ET0=1;
	TR0=1;
}
void time_0()interrupt 1 // timer 1
{
	TH0=(65536-50000)/256;
	TL0=(65536-50000)%256;
	timer_count++;
	if(timer_count == 20)
	{
		// LED=~LED;
		timer_count=0;
		left_time--;
	}
}
/* time set function*/
/*Button*/
void Delay(uint CNT)
{
  uint i;
  while (CNT-- !=0)
  for (i=100; i !=0; i--);
}
void key()
{
   if(P10==0)
   {
		 DelayMS(10);
		 if(P10==0)
		 {
			if(level<8&&p_status)
			{
				level++;
			}
		while(!P10);
		 }
   }
   if(P11==0)
   {
		 DelayMS(10);
		 if(P11==0)
		 {
			 if(level>0&&p_status)
			{
				level--;
			}
		while(!P11);
		 }
      
   }
   if(P12==0)
   {
		 DelayMS(10);
		 if(P12==0)
		 {
			 if(p_status==1)
			{
				 level=0;
				 p_status=0;
			}
			else
			{
				 level=1;
				 p_status=1;
			}
			while(!P12);
		 }
      
   }
	 if (P13 == 0) // on and off
	 {
		 DelayMS(10);
		 if (P13 == 0)
		 {
			 if (on_off == 0)
			 {
				 on_off = 1;
			 }
			 else
			 {
				 on_off = 0;
			 }
			while(!P13);
		 }
		 
	 }
	if (P14 == 0) // on and off
	 {
		 DelayMS(10);
		 if (P14 == 0)
		 {
			if (auto_mode == 0)
			 {
				 auto_mode = 1;
			 }
			 else
			 {
				 auto_mode = 0;
			 }
			while(!P14);
		 }
		 
	 }
	if (P15 == 0) // set time
	 {
		 DelayMS(10);
		 if (P15 == 0)
		 {
			if (set_time_mode == 0)
			 {
				 set_time_mode = 1;
			 }
			 else
			 {
				 set_time_mode = 0;
			 }
			while(!P15);
		 }
		 
	 }
   //while(P10||P11||P12||P13);
	 //while(P1);
}
/*Button*/
/* temperature level function*/
void tem_level()
{
	if (now_temperature <= 27) {level = 1;}
	if (now_temperature > 27 && now_temperature <= 29) {level = 2;}
	if (now_temperature > 29 && now_temperature <= 31) {level = 3;}
	if (now_temperature > 31 && now_temperature <= 33) {level = 4;}
	if (now_temperature > 35 && now_temperature <= 37) {level = 5;}
	if (now_temperature > 37 && now_temperature <= 39) {level = 6;}
	if (now_temperature > 39 && now_temperature <= 41) {level = 7;}
	if (now_temperature > 41) {level = 8;}
}
/* temperature level function*/
void main(void)
 { 
	uint i = 0; // count v
   myinit();//????????

   while (1)
   {
		if (on_off == 1)
		{
			if (auto_mode == 0 && set_time_mode == 0) {
				DACS=DA_LEVEL[level];
				DelayMS(10);
				readADC();
				showkey(now_temperature/10,5);
				DelayMS(2);
				showkey(now_temperature%10,6);
				DelayMS(2);
				showkey(level/10,1);
				showkey(level%10,2);
				showkey(16,3);
				showkey(16,4);
				//showkey(on_off,3);
				key();
			}
			else if (auto_mode == 1 && set_time_mode == 0){
				tem_level();
				DACS=DA_LEVEL[level];
				DelayMS(10);
				readADC();
				showkey(now_temperature/10,5);
				DelayMS(2);
				showkey(now_temperature%10,6);
				DelayMS(2);
				showkey(level/10,1);
				showkey(level%10,2);
				showkey(16,3);
				showkey(16,4);
				key();
			}
			else if (auto_mode == 0 && set_time_mode == 1)
			{
				// myint0();
				init_time();
				while(set_time_mode)
				{
					// time_0();
					if (left_time != 0)
					{
						DACS=DA_LEVEL[level];
						DelayMS(10);
						readADC();
						showkey(now_temperature/10,5);
						DelayMS(2);
						showkey(now_temperature%10,6);
						DelayMS(2);
						showkey(level/10,1);
						showkey(level%10,2);
						showkey(left_time/10,3);
						showkey(left_time%10,4);
						//showkey(on_off,3);
						key();
					}
					else
					{
						on_off = 0;
						set_time_mode = 0;
						auto_mode = 0;
					}
				}
			}
		}
		else
		{
				level = 0;
				DACS=DA_LEVEL[level];
				Delay(10);
				for (i = 1; i < 7; i++) {
					showkey(16,i);
				}
				key();
		}
		
   }
}
void showkey(uchar b,uchar pos)
{
   *DIGIT=SEGLOCAL[pos];
   *SEG=SEGCC[b];
   DelayMS(1);
}
 void readADC()
{
  *ADCS = 0;                // ?? A/D
  DelayMS(1);
  adresult=my_data_ADC0;
  now_temperature=adresult%100;

}
 void DelayMS(uint x) 
{  
   uchar i;
   while(x--)
      {
	 for(i=0;i<60;i++);
      }
}